describe('app opens', function() {
    before(function() {
        cy.request('post', 'http://localhost:3001/api/testing/reset')
    })
    describe('register flow', function() {
        it('user can register', function() {
            cy.visit('http://localhost:3000')
            cy.get('#link-to-register').click()
            cy.get('#register-username').type('testuser')
            cy.get('#register-password').type('password')
            cy.get('#register-button').click()
            cy.contains('user created')
        })
        it('front page opens', function() {
            cy.visit('http://localhost:3000')
            cy.contains('username')
            cy.get('#login-username').type('testuser')
            cy.get('#login-password').type('password')
            cy.get('#login-button').click()
    
            cy.contains('testuser logged in')
            cy.get('#rate-book').children().last().children().first().click()
            cy.get('#sample-ready-button').click()
            cy.contains('Find books')
            cy.contains('Booklists')
            cy.get('#link-to-readlist').click()
            cy.contains('The Great Gatsby')
        })
    })
    describe('test readlist functions', function() {
        it('user can add a readlist', function() {
            cy.visit('http://localhost:3000')
            cy.get('#login-username').type('testuser')
            cy.get('#login-password').type('password')
            cy.get('#login-button').click()
            cy.contains('Booklists')
            cy.get('#add-list-form-btn').click()
            cy.get('#add-list-input').type('unread')
            cy.get('#add-list-btn').click()
            cy.get('#add-list-input').type('interesting')
            cy.get('#add-list-btn').click()
            cy.wait(1000)
            cy.get('a').contains('unread')
        })
        it('add a book to readlist by search', function() {
            cy.get('#search-input').type('9780316015844')
            cy.get('#search-btn').click()
            cy.contains('Twilight')
            cy.contains('Stephenie Meyer')
            cy.contains('unread').click()
        })
        it('changes book on search view and rates it', function() {
            cy.get('#search-input').type('9780316087360')
            cy.get('#search-btn').click()
            cy.contains('Eclipse')
            cy.get('#rating-part').children().children().first().click()
            cy.contains('home').click()
            cy.wait(1000)
            cy.contains('rated').click()
            cy.contains('Eclipse')
            cy.contains('home').click()
            cy.wait(1000)
            cy.contains('unread').click()
            cy.contains('Twilight')
        })
        it('rates books', function() {
            cy.contains('home').click()
            cy.wait(1000)
            cy.get('.readlist-link-box').contains('Debt of Honor').click()
            cy.get('#rating-part').children().children().first().click()
            cy.contains('<').click()
            cy.get('.readlist-link-box').contains('Red Dragon').click()
            cy.contains('unread').click()
            cy.contains('<').click()
        })
        it('changes the list', function() {
            cy.wait(1000)
            cy.contains('rated').click()
            cy.contains('Debt of Honor')
            cy.contains('home').click()
            cy.wait(1000)
            cy.contains('unread').click()
            cy.get('.readlist-link-box').contains('Red Dragon').click()
            cy.contains('<').click()
        })
        it('does not add book to list twice on recommend view', function() {
            cy.contains('home').click()
            cy.wait(1000)
            cy.get('.readlist-link-box').contains('Executive Orders').click()
            cy.contains('unread').click()
            cy.contains('interesting').click()
            cy.contains('<').click()
            cy.contains('interesting').click()
            cy.contains('Executive Orders')
            cy.contains('home').click()
            cy.contains('unread').click()
            cy.get('.page-container').should('contain', 'Red Dragon')
            cy.get('.page-container').should('not.contain', 'Executive Orders')
        })
    })

})