version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build_and_test:
    jobs:
      - db
      - build
      - test
jobs:
  db:
    machine: true
    steps:
      - checkout
      - run: | 
        echo "$DOCKER_PASS"

  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test